# Generated by Django 3.2.4 on 2021-06-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('reciever', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=300)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
