# Generated by Django 3.2.4 on 2021-06-14 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='liked_username',
            new_name='cmt_username',
        ),
    ]
