# Generated by Django 3.2.4 on 2021-06-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friendslist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=-1)),
                ('username', models.CharField(max_length=20)),
                ('friend', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('pro_image', models.ImageField(default='profile/images/default.png', upload_to='profile/images')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
