# Generated by Django 3.2.4 on 2021-06-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendslist',
            name='friend_id',
            field=models.IntegerField(default=-1),
        ),
    ]
